spring.application.name=demo

# Configuracao do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bdAutoCenterSilva
spring.datasource.username=postgres
spring.datasource.password=30102007
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra a mensagem de erro na resposta HTTP
spring.web.error.include-message=always